# Generated by Django 3.1.2 on 2020-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indices',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
