# Generated by Django 3.1.2 on 2020-11-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_indices_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
