# Generated by Django 3.1.2 on 2020-11-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_traders'),
    ]

    operations = [
        migrations.AddField(
            model_name='indices',
            name='volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
