# Generated by Django 3.1.2 on 2020-11-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_indices_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='indices',
            name='dayhigh',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indices',
            name='daylow',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indices',
            name='high',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indices',
            name='low',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indices',
            name='nch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indices',
            name='open',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indices',
            name='pch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
