# Generated by Django 3.1.2 on 2020-11-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_auto_20201114_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indices',
            name='opens',
        ),
        migrations.AddField(
            model_name='indices',
            name='op',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
