# Generated by Django 3.1.2 on 2020-11-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_indices_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold1', models.CharField(max_length=100)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.traders')),
            ],
        ),
    ]
