# Generated by Django 3.1.2 on 2020-11-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0010_holdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
