# Generated by Django 3.1.2 on 2020-11-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0012_scripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalIndices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('dayhigh', models.IntegerField()),
                ('daylow', models.IntegerField()),
                ('nch', models.IntegerField()),
                ('pch', models.IntegerField()),
                ('fact', models.IntegerField()),
            ],
        ),
    ]
