# Generated by Django 3.1.2 on 2020-11-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0013_globalindices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
